# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

assetic:
    bundles:
        - CampaignChainOperationEZPlatformBundle
    assets:
        campaignchain_operation_ezplatform_schedule_css:
            inputs:
                - '@CampaignChainOperationEZPlatformBundle/Resources/public/css/ezplatform_schedule.css'
twig:
    form:
        resources:
            - 'CampaignChainOperationEZPlatformBundle:Form:fields.html.twig'
